{
  "id": "GHSA-3vcg-8p79-jpcv",
  "summary": "Improper Restriction of XML External Entity Reference in svglib",
  "details": "The svglib package through 0.9.3 for Python allows XXE attacks via an svg2rlg call.",
  "aliases": [
    "CVE-2020-10799"
  ],
  "modified": "2023-02-16T23:31:51.247726Z",
  "published": "2021-05-06T18:52:01Z",
  "database_specific": {
    "cwe_ids": [
      "CWE-611"
    ],
    "severity": "HIGH",
    "github_reviewed": true,
    "github_reviewed_at": "2021-05-05T22:26:32Z",
    "nvd_published_at": "2020-03-20T23:15:00Z"
  },
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-10799"
    },
    {
      "type": "WEB",
      "url": "https://github.com/deeplook/svglib/issues/229"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "svglib",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/svglib"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "0.9.4"
            }
          ]
        }
      ],
      "versions": [
        "0.6.0",
        "0.6.1",
        "0.6.2",
        "0.6.3",
        "0.8.0",
        "0.8.1",
        "0.9.0",
        "0.9.0b0",
        "0.9.1",
        "0.9.2",
        "0.9.3"
      ],
      "database_specific": {
        "last_known_affected_version_range": "<= 0.9.3",
        "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/05/GHSA-3vcg-8p79-jpcv/GHSA-3vcg-8p79-jpcv.json"
      }
    }
  ],
  "schema_version": "1.3.0",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    }
  ]
}