{
  "id": "GHSA-33h2-69j3-r336",
  "summary": "Out-of-bounds Read in OpenCV ",
  "details": "OpenCV (Open Source Computer Vision Library) through 3.3 (corresponding to OpenCV-Python 3.3.0.9) has an out-of-bounds read error in the cv::RBaseStream::readBlock function in modules/imgcodecs/src/bitstrm.cpp when reading an image file by using cv::imread, as demonstrated by the 8-opencv-invalid-read-fread test case.",
  "aliases": [
    "CVE-2017-12598"
  ],
  "modified": "2023-02-16T23:15:46.627136Z",
  "published": "2021-10-12T22:00:51Z",
  "database_specific": {
    "cwe_ids": [
      "CWE-125"
    ],
    "severity": "HIGH",
    "github_reviewed": true,
    "github_reviewed_at": "2021-10-08T14:49:53Z",
    "nvd_published_at": "2017-08-07T01:29:00Z"
  },
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2017-12598"
    },
    {
      "type": "WEB",
      "url": "https://github.com/opencv/opencv/issues/9309"
    },
    {
      "type": "WEB",
      "url": "https://github.com/opencv/opencv/pull/9376"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/opencv/opencv-python"
    },
    {
      "type": "WEB",
      "url": "https://github.com/opencv/opencv-python/releases/tag/11"
    },
    {
      "type": "WEB",
      "url": "https://github.com/opencv/opencv-python/releases/tag/9"
    },
    {
      "type": "WEB",
      "url": "https://github.com/xiaoqx/pocs/blob/master/opencv.md"
    },
    {
      "type": "WEB",
      "url": "https://lists.debian.org/debian-lts-announce/2018/07/msg00030.html"
    },
    {
      "type": "WEB",
      "url": "https://lists.debian.org/debian-lts-announce/2021/10/msg00028.html"
    },
    {
      "type": "WEB",
      "url": "https://security.gentoo.org/glsa/201712-02"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "opencv-python",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/opencv-python"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.3.1.11"
            }
          ]
        }
      ],
      "versions": [
        "3.1.0",
        "3.1.0.0",
        "3.1.0.1",
        "3.1.0.2",
        "3.1.0.3",
        "3.1.0.4",
        "3.1.0.5",
        "3.2.0.6",
        "3.2.0.7",
        "3.2.0.8",
        "3.3.0.10",
        "3.3.0.9"
      ],
      "database_specific": {
        "last_known_affected_version_range": "<= 3.3.0.9",
        "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/10/GHSA-33h2-69j3-r336/GHSA-33h2-69j3-r336.json"
      }
    },
    {
      "package": {
        "name": "opencv-contrib-python",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/opencv-contrib-python"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.3.1.11"
            }
          ]
        }
      ],
      "versions": [
        "3.1.0.0",
        "3.2.0.7",
        "3.2.0.8",
        "3.3.0.10",
        "3.3.0.9"
      ],
      "database_specific": {
        "last_known_affected_version_range": "<= 3.3.0.9",
        "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/10/GHSA-33h2-69j3-r336/GHSA-33h2-69j3-r336.json"
      }
    }
  ],
  "schema_version": "1.3.0",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H"
    }
  ]
}