{
  "id": "GHSA-vw39-2wj9-4q86",
  "summary": "django-mfa2 vulnerable to MFA Replay attack",
  "details": "mfa/FIDO2.py in django-mfa2 before 2.5.1 and 2.6.x before 2.6.1 allows a replay attack that could be used to register another device for a user. The device registration challenge is not invalidated after usage.",
  "aliases": [
    "CVE-2022-42731"
  ],
  "modified": "2023-02-16T23:08:39.542405Z",
  "published": "2022-10-11T19:00:29Z",
  "database_specific": {
    "cwe_ids": [
      "CWE-294"
    ],
    "severity": "HIGH",
    "github_reviewed": true,
    "github_reviewed_at": "2022-10-11T20:49:45Z",
    "nvd_published_at": "2022-10-11T14:15:00Z"
  },
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-42731"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/mkalioby/django-mfa2"
    },
    {
      "type": "WEB",
      "url": "https://github.com/mkalioby/django-mfa2/blob/0936ea253354dd95cb127f09d0efa31324caef27/mfa/FIDO2.py#L58"
    },
    {
      "type": "WEB",
      "url": "https://github.com/mkalioby/django-mfa2/releases/tag/v2.5.1-release"
    },
    {
      "type": "WEB",
      "url": "https://github.com/mkalioby/django-mfa2/releases/tag/v2.6.1-release"
    },
    {
      "type": "WEB",
      "url": "https://github.com/pypa/advisory-database/tree/main/vulns/django-mfa2/PYSEC-2022-303.yaml"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "django-mfa2",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/django-mfa2"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2.5.1"
            }
          ]
        }
      ],
      "versions": [
        "0.8",
        "0.8.5",
        "0.8.7",
        "0.8.8",
        "0.9.0",
        "0.9.1",
        "0.9.2",
        "0.9.4",
        "0.9.5",
        "1.0",
        "1.0.1",
        "1.0.2",
        "1.0.3",
        "1.0.4",
        "1.0.5",
        "1.1",
        "1.1.1",
        "1.1.2",
        "1.1.5",
        "1.1.6",
        "1.1.7",
        "1.1.8",
        "1.1.8.1",
        "1.2.0",
        "1.2.1",
        "1.3.0",
        "1.4.0",
        "1.4.1",
        "1.5.0",
        "1.6",
        "1.7.0",
        "1.7.10",
        "1.7.11",
        "1.7.12",
        "1.7.13",
        "1.7.5",
        "1.7.6",
        "1.7.7",
        "1.7.8",
        "1.7.9",
        "1.8.0",
        "1.8.1",
        "1.9.0",
        "2.0.0",
        "2.0.1",
        "2.0.2",
        "2.0.3",
        "2.0.4",
        "2.0.5",
        "2.0.6",
        "2.1.0",
        "2.1.2",
        "2.1.2b1",
        "2.2.0",
        "2.2.0b1",
        "2.2.0b2",
        "2.3.0",
        "2.4.0",
        "2.5.0",
        "2.5.0b1",
        "2.5.0b2"
      ],
      "database_specific": {
        "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2022/10/GHSA-vw39-2wj9-4q86/GHSA-vw39-2wj9-4q86.json"
      }
    },
    {
      "package": {
        "name": "django-mfa2",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/django-mfa2"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "2.6.0"
            },
            {
              "fixed": "2.6.1"
            }
          ]
        }
      ],
      "versions": [
        "2.6.0"
      ],
      "database_specific": {
        "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2022/10/GHSA-vw39-2wj9-4q86/GHSA-vw39-2wj9-4q86.json"
      }
    }
  ],
  "schema_version": "1.3.0",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N"
    }
  ]
}