{
  "id": "GHSA-fr58-2xhv-qp3w",
  "summary": "Denial of Service in OpenCV",
  "details": "OpenCV (Open Source Computer Vision Library) through 3.3 (corresponding to OpenCV-Python 3.3.0.9) has a denial of service (CPU consumption) issue, as demonstrated by the 11-opencv-dos-cpu-exhaust test case.",
  "aliases": [
    "CVE-2017-12600"
  ],
  "modified": "2023-02-16T23:28:05.421111Z",
  "published": "2021-10-12T22:01:16Z",
  "database_specific": {
    "cwe_ids": [],
    "severity": "HIGH",
    "github_reviewed": true,
    "github_reviewed_at": "2021-10-08T14:44:47Z",
    "nvd_published_at": null
  },
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2017-12600"
    },
    {
      "type": "WEB",
      "url": "https://github.com/opencv/opencv/issues/9311"
    },
    {
      "type": "WEB",
      "url": "https://github.com/opencv/opencv/pull/9376"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/opencv/opencv-python"
    },
    {
      "type": "WEB",
      "url": "https://github.com/opencv/opencv-python/releases/tag/11"
    },
    {
      "type": "WEB",
      "url": "https://github.com/opencv/opencv-python/releases/tag/9"
    },
    {
      "type": "WEB",
      "url": "https://github.com/xiaoqx/pocs/blob/master/opencv.md"
    },
    {
      "type": "WEB",
      "url": "https://security.gentoo.org/glsa/201712-02"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "opencv-python",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/opencv-python"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.3.1.11"
            }
          ]
        }
      ],
      "versions": [
        "3.1.0",
        "3.1.0.0",
        "3.1.0.1",
        "3.1.0.2",
        "3.1.0.3",
        "3.1.0.4",
        "3.1.0.5",
        "3.2.0.6",
        "3.2.0.7",
        "3.2.0.8",
        "3.3.0.10",
        "3.3.0.9"
      ],
      "database_specific": {
        "last_known_affected_version_range": "<= 3.3.0.9",
        "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/10/GHSA-fr58-2xhv-qp3w/GHSA-fr58-2xhv-qp3w.json"
      }
    },
    {
      "package": {
        "name": "opencv-contrib-python",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/opencv-contrib-python"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.3.1.11"
            }
          ]
        }
      ],
      "versions": [
        "3.1.0.0",
        "3.2.0.7",
        "3.2.0.8",
        "3.3.0.10",
        "3.3.0.9"
      ],
      "database_specific": {
        "last_known_affected_version_range": "<= 3.3.0.9",
        "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/10/GHSA-fr58-2xhv-qp3w/GHSA-fr58-2xhv-qp3w.json"
      }
    }
  ],
  "schema_version": "1.3.0",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  ]
}