{
  "id": "GHSA-cvhw-2593-5j2q",
  "summary": "Double Free in OpenCV",
  "details": "OpenCV 3.0.0 has a double free issue that allows attackers to execute arbitrary code. This issue was fixed in OpenCV version 3.3.1 (corresponding to OpenCV-Python and and OpenCV-Contrib-Python 3.3.1.11).",
  "aliases": [
    "CVE-2016-1516"
  ],
  "modified": "2023-02-16T23:15:45.082410Z",
  "published": "2021-10-12T22:00:08Z",
  "database_specific": {
    "cwe_ids": [
      "CWE-415"
    ],
    "severity": "HIGH",
    "github_reviewed": true,
    "github_reviewed_at": "2021-10-08T18:44:07Z",
    "nvd_published_at": "2017-04-10T03:59:00Z"
  },
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2016-1516"
    },
    {
      "type": "WEB",
      "url": "https://github.com/opencv/opencv/issues/5956"
    },
    {
      "type": "WEB",
      "url": "https://github.com/opencv/opencv/pull/9376"
    },
    {
      "type": "WEB",
      "url": "https://arxiv.org/pdf/1701.04739.pdf"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/opencv/opencv-python"
    },
    {
      "type": "WEB",
      "url": "https://lists.debian.org/debian-lts-announce/2018/07/msg00030.html"
    },
    {
      "type": "WEB",
      "url": "https://lists.debian.org/debian-lts-announce/2021/10/msg00028.html"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "opencv-python",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/opencv-python"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.3.1.11"
            }
          ]
        }
      ],
      "versions": [
        "3.1.0",
        "3.1.0.0",
        "3.1.0.1",
        "3.1.0.2",
        "3.1.0.3",
        "3.1.0.4",
        "3.1.0.5",
        "3.2.0.6",
        "3.2.0.7",
        "3.2.0.8",
        "3.3.0.10",
        "3.3.0.9"
      ],
      "database_specific": {
        "last_known_affected_version_range": "<= 3.3.0.10",
        "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/10/GHSA-cvhw-2593-5j2q/GHSA-cvhw-2593-5j2q.json"
      }
    },
    {
      "package": {
        "name": "opencv-contrib-python",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/opencv-contrib-python"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.3.1.11"
            }
          ]
        }
      ],
      "versions": [
        "3.1.0.0",
        "3.2.0.7",
        "3.2.0.8",
        "3.3.0.10",
        "3.3.0.9"
      ],
      "database_specific": {
        "last_known_affected_version_range": "<= 3.3.0.10",
        "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/10/GHSA-cvhw-2593-5j2q/GHSA-cvhw-2593-5j2q.json"
      }
    }
  ],
  "schema_version": "1.3.0",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H"
    }
  ]
}