{
  "id": "GHSA-rfw2-x9f8-2f6m",
  "summary": "Cross-Site Scripting",
  "details": "LinkedIn Oncall through 1.4.0 allows reflected XSS via /query because of mishandling of the \"No results found for\" message in the search bar.",
  "aliases": [
    "CVE-2021-26722"
  ],
  "modified": "2023-02-16T23:29:04.704713Z",
  "published": "2021-04-30T17:27:53Z",
  "database_specific": {
    "cwe_ids": [
      "CWE-79"
    ],
    "severity": "MODERATE",
    "github_reviewed": true,
    "github_reviewed_at": "2021-04-28T19:21:42Z",
    "nvd_published_at": "2021-02-05T18:15:00Z"
  },
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-26722"
    },
    {
      "type": "WEB",
      "url": "https://github.com/linkedin/oncall/issues/341"
    },
    {
      "type": "WEB",
      "url": "https://github.com/linkedin/oncall/commit/843bc106a1c1b1699e9e52b6b0d01c7efe1d6225"
    },
    {
      "type": "WEB",
      "url": "https://pypi.org/project/oncall/"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "oncall",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/oncall"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "1.4.1"
            }
          ]
        }
      ],
      "versions": [
        "1.1.10",
        "1.1.2",
        "1.1.3",
        "1.1.4",
        "1.1.5",
        "1.1.7",
        "1.1.8",
        "1.1.9",
        "1.2.0",
        "1.2.1",
        "1.2.2",
        "1.2.3",
        "1.2.4",
        "1.3.4",
        "1.3.5",
        "1.3.6",
        "1.3.7",
        "1.3.8",
        "1.3.9",
        "1.4.0"
      ],
      "database_specific": {
        "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/04/GHSA-rfw2-x9f8-2f6m/GHSA-rfw2-x9f8-2f6m.json"
      }
    }
  ],
  "schema_version": "1.3.0"
}