{
  "id": "PYSEC-2022-250",
  "details": "The exotel project on PyPI was taken over via user account compromise via a phishing attack and a new malicious release made which contained code which some environment variables and downloaded and ran malware at install time",
  "modified": "2022-08-26T17:55:00Z",
  "published": "2022-08-26T17:55:00Z",
  "references": [
    {
      "type": "ARTICLE",
      "url": "https://twitter.com/pypi/status/1562442207079976966"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "exotel",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/exotel"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0.1.6"
            }
          ]
        }
      ],
      "versions": [
        "0.1.6"
      ],
      "database_specific": {
        "source": "https://github.com/pypa/advisory-database/blob/main/vulns/exotel/PYSEC-2022-250.yaml"
      }
    }
  ],
  "schema_version": "1.3.0"
}