{
  "id": "PYSEC-2019-235",
  "details": "NULL pointer dereference in Google TensorFlow before 1.12.2 could cause a denial of service via an invalid GIF file.",
  "aliases": [
    "CVE-2019-9635"
  ],
  "modified": "2021-12-09T06:35:11.945126Z",
  "published": "2019-04-24T17:29:00Z",
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/tensorflow/tensorflow/blob/master/tensorflow/security/advisory/tfsa-2019-001.md"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "tensorflow-gpu",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/tensorflow-gpu"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "1.12.2"
            }
          ]
        }
      ],
      "versions": [
        "0.12.0",
        "0.12.1",
        "1.0.0",
        "1.0.1",
        "1.1.0",
        "1.10.0",
        "1.10.1",
        "1.11.0",
        "1.12.0",
        "1.2.0",
        "1.2.1",
        "1.3.0",
        "1.4.0",
        "1.4.1",
        "1.5.0",
        "1.5.1",
        "1.6.0",
        "1.7.0",
        "1.7.1",
        "1.8.0",
        "1.9.0"
      ],
      "database_specific": {
        "source": "https://github.com/pypa/advisory-database/blob/main/vulns/tensorflow-gpu/PYSEC-2019-235.yaml"
      }
    }
  ],
  "schema_version": "1.3.0"
}