{
  "id": "PYSEC-2020-87",
  "details": "plone.restapi in Plone 5.2.0 through 5.2.1 allows users with a certain privilege level to escalate their privileges up to the highest level.",
  "aliases": [
    "CVE-2020-7938"
  ],
  "modified": "2020-01-24T23:03:00Z",
  "published": "2020-01-23T21:15:00Z",
  "references": [
    {
      "type": "WEB",
      "url": "https://plone.org/security/hotfix/20200121"
    },
    {
      "type": "WEB",
      "url": "https://plone.org/security/hotfix/20200121/privilege-escalation-when-plone-restapi-is-installed"
    },
    {
      "type": "WEB",
      "url": "https://www.openwall.com/lists/oss-security/2020/01/22/1"
    },
    {
      "type": "WEB",
      "url": "http://www.openwall.com/lists/oss-security/2020/01/24/1"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "plone",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/plone"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "5.2.0"
            },
            {
              "fixed": "5.2.2"
            }
          ]
        }
      ],
      "versions": [
        "5.2.0",
        "5.2.1"
      ],
      "database_specific": {
        "source": "https://github.com/pypa/advisory-database/blob/main/vulns/plone/PYSEC-2020-87.yaml"
      }
    }
  ],
  "schema_version": "1.3.0"
}